[package]
name = "demo-axum"
default-run = "demo-axum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = { path = "../crates/db" }
migration = { path = "../crates/migration" }
api = { path = "../crates/api" }

axum = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
sea-orm = { workspace = true }
dotenvy = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true}
tower = { workspace = true }
aide = { workspace = true }
tower-http = { workspace = true }