services:
  postgres:
    image: postgres:15-bullseye
    container_name: demo-axum-postgres
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    volumes:
      - demo-axum-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  demo-axum-postgres: {}
